spring:
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  name:
    producer: deploy.ambiente.dev
    group_id: teste

deploy:
  ambiente:
    dev: deploy.ambiente.dev
    hom: deploy.ambiente.hom
    prod: deploy.ambiente.prod