spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:deploy-weblogic-api-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topic:
  name:
    producer: deploy.ambiente.dev

deploy:
  grupo-id: deploy-weblogic-api
  ambiente:
    dev: deploy.ambiente.dev
    hom: deploy.ambiente.hom
    prod: deploy.ambiente.prod

servico:
  nexus:
    url: "https://nexus.sefa.pa.gov.br/repository/maven-public"