CREATE SCHEMA IF NOT EXISTS DEPLOY;

CREATE TABLE DEPLOY.TAB_AMBIENTE
(
    AMBIENTE_ID       int8        NOT NULL,
    AMBIENTE          varchar(15) NOT NULL,
    AMBIENTE_RESUMIDO varchar(5)  NOT NULL,
    CONSTRAINT TAB_AMBIENTE_PK PRIMARY KEY (AMBIENTE_ID)
);

CREATE TABLE DEPLOY.TAB_SERVIDOR
(
    SERVIDOR_ID       int8        NOT NULL,
    SERVIDOR_ENDERECO varchar(15) NOT NULL,
    AMBIENTE_ID       int8        NOT NULL,
    CONSTRAINT TAB_SERVIDOR_PK PRIMARY KEY (SERVIDOR_ID)
);

insert into DEPLOY.TAB_AMBIENTE(AMBIENTE_ID, AMBIENTE, AMBIENTE_RESUMIDO)
values (1, 'desenvolvimento', 'dev');
insert into DEPLOY.TAB_AMBIENTE(AMBIENTE_ID, AMBIENTE, AMBIENTE_RESUMIDO)
values (2, 'homologacao', 'hom');
insert into DEPLOY.TAB_AMBIENTE(AMBIENTE_ID, AMBIENTE, AMBIENTE_RESUMIDO)
values (3, 'producao', 'prod');

insert into DEPLOY.TAB_SERVIDOR(SERVIDOR_ID, SERVIDOR_ENDERECO, AMBIENTE_ID)
values (1, '10.3.3.100', 1);