CREATE SCHEMA IF NOT EXISTS DEPLOY;

CREATE TABLE DEPLOY.TAB_AMBIENTE
(
    AMBIENTE_ID       int8        NOT NULL,
    AMBIENTE          varchar(15) NOT NULL,
    AMBIENTE_RESUMIDO varchar(5)  NOT NULL,
    CONSTRAINT TAB_AMBIENTE_PK PRIMARY KEY (AMBIENTE_ID)
);

CREATE TABLE DEPLOY.TAB_SERVIDOR
(
    SERVIDOR_ID       int8        NOT NULL,
    SERVIDOR_ENDERECO varchar(15) NOT NULL,
    AMBIENTE_ID       int8        NOT NULL,
    CONSTRAINT TAB_SERVIDOR_PK PRIMARY KEY (SERVIDOR_ID)
);

CREATE TABLE DEPLOY.TAB_APLICACAO
(
    APLICACAO_ID            int8        NOT NULL,
    APLICACAO_DESCRICAO     varchar(15) NOT NULL,
    APLICACAO_SERVIDOR_DEV  int8        NOT NULL,
    APLICACAO_SERVIDOR_HOM  int8        NOT NULL,
    APLICACAO_SERVIDOR_PROD int8        NOT NULL,
    CONSTRAINT TAB_APLICACAO_PK PRIMARY KEY (APLICACAO_ID)
);

insert into DEPLOY.TAB_AMBIENTE(AMBIENTE_ID, AMBIENTE, AMBIENTE_RESUMIDO)
values (1, 'desenvolvimento', 'dev');
insert into DEPLOY.TAB_AMBIENTE(AMBIENTE_ID, AMBIENTE, AMBIENTE_RESUMIDO)
values (2, 'homologacao', 'hom');
insert into DEPLOY.TAB_AMBIENTE(AMBIENTE_ID, AMBIENTE, AMBIENTE_RESUMIDO)
values (3, 'producao', 'prod');

insert into DEPLOY.TAB_SERVIDOR(SERVIDOR_ID, SERVIDOR_ENDERECO, AMBIENTE_ID)
values (1, '10.1.1.100', 1);
insert into DEPLOY.TAB_SERVIDOR(SERVIDOR_ID, SERVIDOR_ENDERECO, AMBIENTE_ID)
values (2, '10.1.1.200', 2);
insert into DEPLOY.TAB_SERVIDOR(SERVIDOR_ID, SERVIDOR_ENDERECO, AMBIENTE_ID)
values (3, '10.1.1.300', 3);

insert into DEPLOY.TAB_APLICACAO(APLICACAO_ID, APLICACAO_DESCRICAO, APLICACAO_SERVIDOR_DEV, APLICACAO_SERVIDOR_HOM,
                                 APLICACAO_SERVIDOR_PROD)
values (1, 'gestao-rh', 1, 2, 3)